// Shared tools data that can be used for seeding and reference
export const initialToolsData = [
  {
    name: 'ChatGPT',
    description: 'Advanced AI chatbot by OpenAI for conversations, writing, and problem-solving',
    category: 'Text AI',
    website_url: 'https://chat.openai.com',
    logo_url: 'https://logo.clearbit.com/openai.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Conversational AI', 'Code generation', 'Text completion', 'Multi-language support'],
    use_cases: ['Writing assistance', 'Coding help', 'Research', 'Content creation'],
    tags: ['chatbot', 'gpt', 'openai', 'writing'],
  },
  {
    name: 'Claude',
    description: 'Anthropic\'s AI assistant focused on helpful, harmless, and honest responses',
    category: 'Text AI',
    website_url: 'https://claude.ai',
    logo_url: 'https://logo.clearbit.com/anthropic.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Long context', 'Document analysis', 'Writing assistance', 'Code generation'],
    use_cases: ['Document analysis', 'Writing', 'Research', 'Coding'],
    tags: ['anthropic', 'assistant', 'writing'],
  },
  {
    name: 'Perplexity',
    description: 'AI-powered search engine that provides answers with citations',
    category: 'Text AI',
    website_url: 'https://perplexity.ai',
    logo_url: 'https://logo.clearbit.com/perplexity.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['AI search', 'Citations', 'Real-time data', 'Multi-source answers'],
    use_cases: ['Research', 'Fact-checking', 'Information gathering'],
    tags: ['search', 'research', 'ai'],
  },
  {
    name: 'Gemini',
    description: 'Google\'s multimodal AI model for text, images, and more',
    category: 'Text AI',
    website_url: 'https://gemini.google.com',
    logo_url: 'https://logo.clearbit.com/google.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Available' },
    features: ['Multimodal', 'Image understanding', 'Code generation', 'Google integration'],
    use_cases: ['Multimodal tasks', 'Google Workspace integration', 'Research'],
    tags: ['google', 'multimodal', 'assistant'],
  },
  {
    name: 'Midjourney',
    description: 'AI art generator known for high-quality, artistic images',
    category: 'Image AI',
    website_url: 'https://midjourney.com',
    logo_url: 'https://logo.clearbit.com/midjourney.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10' },
    features: ['Art generation', 'Style control', 'High resolution', 'Community features'],
    use_cases: ['Digital art', 'Concept art', 'Illustrations', 'Creative projects'],
    tags: ['art', 'generation', 'creative'],
  },
  {
    name: 'DALL-E',
    description: 'OpenAI\'s image generation model for creating images from text descriptions',
    category: 'Image AI',
    website_url: 'https://openai.com/dall-e-3',
    logo_url: 'https://logo.clearbit.com/openai.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: 'Pay per image' },
    features: ['Text-to-image', 'High quality', 'Safe generation', 'Multiple styles'],
    use_cases: ['Image creation', 'Design', 'Marketing materials', 'Concept visualization'],
    tags: ['openai', 'image-generation', 'art'],
  },
  {
    name: 'Stable Diffusion',
    description: 'Open-source image generation model with extensive customization',
    category: 'Image AI',
    website_url: 'https://stability.ai',
    logo_url: 'https://logo.clearbit.com/stability.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Varies', free_tier: 'Self-hosted available' },
    features: ['Open source', 'Customizable', 'ControlNet', 'Multiple models'],
    use_cases: ['Custom image generation', 'Research', 'Commercial use'],
    tags: ['open-source', 'stable-diffusion', 'customizable'],
  },
  {
    name: 'Leonardo.ai',
    description: 'AI image generation platform with advanced control features',
    category: 'Image AI',
    website_url: 'https://leonardo.ai',
    logo_url: 'https://logo.clearbit.com/leonardo.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Image generation', 'Model training', 'Control features', 'API access'],
    use_cases: ['Game assets', 'Marketing images', 'Creative projects'],
    tags: ['generation', 'control', 'gaming'],
  },
  {
    name: 'Runway',
    description: 'AI video generation and editing platform',
    category: 'Video AI',
    website_url: 'https://runwayml.com',
    logo_url: 'https://logo.clearbit.com/runwayml.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: 'Limited' },
    features: ['Video generation', 'Video editing', 'Motion tracking', 'Green screen'],
    use_cases: ['Video creation', 'Editing', 'Motion graphics', 'Content creation'],
    tags: ['video', 'editing', 'generation'],
  },
  {
    name: 'Pika',
    description: 'AI video generation tool for creating short videos from text or images',
    category: 'Video AI',
    website_url: 'https://pika.art',
    logo_url: 'https://logo.clearbit.com/pika.art',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Text-to-video', 'Image-to-video', 'Style control', 'Fast generation'],
    use_cases: ['Short videos', 'Social media', 'Animations', 'Content creation'],
    tags: ['video', 'generation', 'social-media'],
  },
  {
    name: 'Synthesia',
    description: 'AI video generation with virtual avatars for presentations and training',
    category: 'Video AI',
    website_url: 'https://synthesia.io',
    logo_url: 'https://logo.clearbit.com/synthesia.io',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$30' },
    features: ['AI avatars', 'Multi-language', 'Custom avatars', 'Template library'],
    use_cases: ['Training videos', 'Presentations', 'Marketing videos', 'E-learning'],
    tags: ['avatars', 'presentations', 'training'],
  },
  {
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code as you type',
    category: 'Code AI',
    website_url: 'https://github.com/features/copilot',
    logo_url: 'https://logo.clearbit.com/github.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10' },
    features: ['Code completion', 'Multi-language', 'IDE integration', 'Context awareness'],
    use_cases: ['Coding', 'Development', 'Learning', 'Productivity'],
    tags: ['github', 'coding', 'ide'],
  },
  {
    name: 'Cursor',
    description: 'AI-powered code editor built for pair programming',
    category: 'Code AI',
    website_url: 'https://cursor.sh',
    logo_url: 'https://logo.clearbit.com/cursor.sh',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['AI editor', 'Code generation', 'Chat interface', 'Multi-file editing'],
    use_cases: ['Development', 'Code review', 'Refactoring', 'Learning'],
    tags: ['editor', 'coding', 'ai'],
  },
  {
    name: 'Tabnine',
    description: 'AI code completion tool supporting multiple IDEs and languages',
    category: 'Code AI',
    website_url: 'https://www.tabnine.com',
    logo_url: 'https://logo.clearbit.com/tabnine.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited' },
    features: ['Code completion', 'Multi-IDE', 'Private code', 'Team features'],
    use_cases: ['Coding', 'Development', 'Team collaboration'],
    tags: ['completion', 'ide', 'coding'],
  },
  {
    name: 'Codeium',
    description: 'Free AI code completion and chat for developers',
    category: 'Code AI',
    website_url: 'https://codeium.com',
    logo_url: 'https://logo.clearbit.com/codeium.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Code completion', 'Free tier', 'Multi-language', 'IDE support'],
    use_cases: ['Coding', 'Development', 'Learning'],
    tags: ['free', 'completion', 'coding'],
  },
  {
    name: 'Jasper',
    description: 'AI writing assistant for marketing and content creation',
    category: 'Text AI',
    website_url: 'https://jasper.ai',
    logo_url: 'https://logo.clearbit.com/jasper.ai',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$49' },
    features: ['Content writing', 'SEO optimization', 'Templates', 'Brand voice'],
    use_cases: ['Marketing', 'Content creation', 'Blog writing', 'Social media'],
    tags: ['writing', 'marketing', 'content'],
  },
  {
    name: 'Copy.ai',
    description: 'AI copywriting tool for marketing and sales',
    category: 'Text AI',
    website_url: 'https://copy.ai',
    logo_url: 'https://logo.clearbit.com/copy.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$49', free_tier: 'Limited' },
    features: ['Copywriting', 'Templates', 'Multi-language', 'Workflows'],
    use_cases: ['Marketing copy', 'Sales emails', 'Social media', 'Ads'],
    tags: ['copywriting', 'marketing', 'sales'],
  },
  {
    name: 'Grammarly',
    description: 'AI-powered writing assistant for grammar and style',
    category: 'Text AI',
    website_url: 'https://grammarly.com',
    logo_url: 'https://logo.clearbit.com/grammarly.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Basic' },
    features: ['Grammar check', 'Style suggestions', 'Tone detection', 'Plagiarism check'],
    use_cases: ['Writing', 'Editing', 'Professional communication'],
    tags: ['grammar', 'writing', 'editing'],
  },
  {
    name: 'ElevenLabs',
    description: 'AI voice generation and text-to-speech platform',
    category: 'Audio AI',
    website_url: 'https://elevenlabs.io',
    logo_url: 'https://logo.clearbit.com/elevenlabs.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: 'Limited' },
    features: ['Voice cloning', 'Text-to-speech', 'Voice library', 'Multi-language'],
    use_cases: ['Voiceovers', 'Audiobooks', 'Podcasts', 'Content creation'],
    tags: ['voice', 'audio', 'tts'],
  },
  {
    name: 'Character.ai',
    description: 'AI chatbot platform with customizable characters',
    category: 'Text AI',
    website_url: 'https://character.ai',
    logo_url: 'https://logo.clearbit.com/character.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Available' },
    features: ['Character creation', 'Conversations', 'Roleplay', 'Custom personalities'],
    use_cases: ['Entertainment', 'Roleplay', 'Creative writing', 'Chat'],
    tags: ['chatbot', 'characters', 'entertainment'],
  },
  {
    name: 'Zapier',
    description: 'AI-powered workflow automation platform',
    category: 'Productivity AI',
    website_url: 'https://zapier.com',
    logo_url: 'https://logo.clearbit.com/zapier.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited tasks' },
    features: ['Workflow automation', 'AI actions', 'App integrations', 'No-code'],
    use_cases: ['Automation', 'Workflows', 'Integration', 'Productivity'],
    tags: ['automation', 'zapier', 'workflows'],
  },
  {
    name: 'Otter.ai',
    description: 'AI meeting assistant with transcription and notes',
    category: 'Productivity AI',
    website_url: 'https://otter.ai',
    logo_url: 'https://logo.clearbit.com/otter.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited minutes' },
    features: ['Live transcription', 'Meeting notes', 'Action items', 'Integration'],
    use_cases: ['Meetings', 'Interviews', 'Lectures', 'Note-taking'],
    tags: ['transcription', 'meetings', 'notes'],
  },
];
