// Database seeding script for initial AI tools
// Run this after setting up Supabase

import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { slugify } from '../lib/tools';
import * as path from 'path';
import * as fs from 'fs';

// Load environment variables from .env.local
const envPath = path.join(__dirname, '../.env.local');
if (fs.existsSync(envPath)) {
  config({ path: envPath });
} else {
  // Fallback to .env if .env.local doesn't exist
  config();
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseKey) {
  console.error('Error: Missing Supabase credentials in .env.local');
  console.error('Please make sure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const initialTools = [
  // Text AI
  {
    name: 'ChatGPT',
    description: 'Advanced AI chatbot by OpenAI for conversations, writing, and problem-solving',
    category: 'Text AI',
    website_url: 'https://chat.openai.com',
    logo_url: 'https://logo.clearbit.com/openai.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Conversational AI', 'Code generation', 'Text completion', 'Multi-language support'],
    use_cases: ['Writing assistance', 'Coding help', 'Research', 'Content creation'],
    tags: ['chatbot', 'gpt', 'openai', 'writing'],
  },
  {
    name: 'Claude',
    description: 'Anthropic\'s AI assistant focused on helpful, harmless, and honest responses',
    category: 'Text AI',
    website_url: 'https://claude.ai',
    logo_url: 'https://logo.clearbit.com/anthropic.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['Long context', 'Document analysis', 'Writing assistance', 'Code generation'],
    use_cases: ['Document analysis', 'Writing', 'Research', 'Coding'],
    tags: ['anthropic', 'assistant', 'writing'],
  },
  {
    name: 'Perplexity',
    description: 'AI-powered search engine that provides answers with citations',
    category: 'Text AI',
    website_url: 'https://perplexity.ai',
    logo_url: 'https://logo.clearbit.com/perplexity.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['AI search', 'Citations', 'Real-time data', 'Multi-source answers'],
    use_cases: ['Research', 'Fact-checking', 'Information gathering'],
    tags: ['search', 'research', 'ai'],
  },
  {
    name: 'Gemini',
    description: 'Google\'s multimodal AI model for text, images, and more',
    category: 'Text AI',
    website_url: 'https://gemini.google.com',
    logo_url: 'https://logo.clearbit.com/google.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Available' },
    features: ['Multimodal', 'Image understanding', 'Code generation', 'Google integration'],
    use_cases: ['Multimodal tasks', 'Google Workspace integration', 'Research'],
    tags: ['google', 'multimodal', 'assistant'],
  },
  // Image AI
  {
    name: 'Midjourney',
    description: 'AI art generator known for high-quality, artistic images',
    category: 'Image AI',
    website_url: 'https://midjourney.com',
    logo_url: 'https://logo.clearbit.com/midjourney.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10' },
    features: ['Art generation', 'Style control', 'High resolution', 'Community features'],
    use_cases: ['Digital art', 'Concept art', 'Illustrations', 'Creative projects'],
    tags: ['art', 'generation', 'creative'],
  },
  {
    name: 'DALL-E',
    description: 'OpenAI\'s image generation model for creating images from text descriptions',
    category: 'Image AI',
    website_url: 'https://openai.com/dall-e-3',
    logo_url: 'https://logo.clearbit.com/openai.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: 'Pay per image' },
    features: ['Text-to-image', 'High quality', 'Safe generation', 'Multiple styles'],
    use_cases: ['Image creation', 'Design', 'Marketing materials', 'Concept visualization'],
    tags: ['openai', 'image-generation', 'art'],
  },
  {
    name: 'Stable Diffusion',
    description: 'Open-source image generation model with extensive customization',
    category: 'Image AI',
    website_url: 'https://stability.ai',
    logo_url: 'https://logo.clearbit.com/stability.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Varies', free_tier: 'Self-hosted available' },
    features: ['Open source', 'Customizable', 'ControlNet', 'Multiple models'],
    use_cases: ['Custom image generation', 'Research', 'Commercial use'],
    tags: ['open-source', 'stable-diffusion', 'customizable'],
  },
  {
    name: 'Leonardo.ai',
    description: 'AI image generation platform with advanced control features',
    category: 'Image AI',
    website_url: 'https://leonardo.ai',
    logo_url: 'https://logo.clearbit.com/leonardo.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Image generation', 'Model training', 'Control features', 'API access'],
    use_cases: ['Game assets', 'Marketing images', 'Creative projects'],
    tags: ['generation', 'control', 'gaming'],
  },
  // Video AI
  {
    name: 'Runway',
    description: 'AI video generation and editing platform',
    category: 'Video AI',
    website_url: 'https://runwayml.com',
    logo_url: 'https://logo.clearbit.com/runwayml.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$15', free_tier: 'Limited' },
    features: ['Video generation', 'Video editing', 'Motion tracking', 'Green screen'],
    use_cases: ['Video creation', 'Editing', 'Motion graphics', 'Content creation'],
    tags: ['video', 'editing', 'generation'],
  },
  {
    name: 'Pika',
    description: 'AI video generation tool for creating short videos from text or images',
    category: 'Video AI',
    website_url: 'https://pika.art',
    logo_url: 'https://logo.clearbit.com/pika.art',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Text-to-video', 'Image-to-video', 'Style control', 'Fast generation'],
    use_cases: ['Short videos', 'Social media', 'Animations', 'Content creation'],
    tags: ['video', 'generation', 'social-media'],
  },
  {
    name: 'Synthesia',
    description: 'AI video generation with virtual avatars for presentations and training',
    category: 'Video AI',
    website_url: 'https://synthesia.io',
    logo_url: 'https://logo.clearbit.com/synthesia.io',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$30' },
    features: ['AI avatars', 'Multi-language', 'Custom avatars', 'Template library'],
    use_cases: ['Training videos', 'Presentations', 'Marketing videos', 'E-learning'],
    tags: ['avatars', 'presentations', 'training'],
  },
  // Code AI
  {
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code as you type',
    category: 'Code AI',
    website_url: 'https://github.com/features/copilot',
    logo_url: 'https://logo.clearbit.com/github.com',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10' },
    features: ['Code completion', 'Multi-language', 'IDE integration', 'Context awareness'],
    use_cases: ['Coding', 'Development', 'Learning', 'Productivity'],
    tags: ['github', 'coding', 'ide'],
  },
  {
    name: 'Cursor',
    description: 'AI-powered code editor built for pair programming',
    category: 'Code AI',
    website_url: 'https://cursor.sh',
    logo_url: 'https://logo.clearbit.com/cursor.sh',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited' },
    features: ['AI editor', 'Code generation', 'Chat interface', 'Multi-file editing'],
    use_cases: ['Development', 'Code review', 'Refactoring', 'Learning'],
    tags: ['editor', 'coding', 'ai'],
  },
  {
    name: 'Tabnine',
    description: 'AI code completion tool supporting multiple IDEs and languages',
    category: 'Code AI',
    website_url: 'https://www.tabnine.com',
    logo_url: 'https://logo.clearbit.com/tabnine.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited' },
    features: ['Code completion', 'Multi-IDE', 'Private code', 'Team features'],
    use_cases: ['Coding', 'Development', 'Team collaboration'],
    tags: ['completion', 'ide', 'coding'],
  },
  {
    name: 'Codeium',
    description: 'Free AI code completion and chat for developers',
    category: 'Code AI',
    website_url: 'https://codeium.com',
    logo_url: 'https://logo.clearbit.com/codeium.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Code completion', 'Free tier', 'Multi-language', 'IDE support'],
    use_cases: ['Coding', 'Development', 'Learning'],
    tags: ['free', 'completion', 'coding'],
  },
  {
    name: 'Jasper',
    description: 'AI writing assistant for marketing and content creation',
    category: 'Text AI',
    website_url: 'https://jasper.ai',
    logo_url: 'https://logo.clearbit.com/jasper.ai',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$49' },
    features: ['Content writing', 'SEO optimization', 'Templates', 'Brand voice'],
    use_cases: ['Marketing', 'Content creation', 'Blog writing', 'Social media'],
    tags: ['writing', 'marketing', 'content'],
  },
  {
    name: 'Copy.ai',
    description: 'AI copywriting tool for marketing and sales',
    category: 'Text AI',
    website_url: 'https://copy.ai',
    logo_url: 'https://logo.clearbit.com/copy.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$49', free_tier: 'Limited' },
    features: ['Copywriting', 'Templates', 'Multi-language', 'Workflows'],
    use_cases: ['Marketing copy', 'Sales emails', 'Social media', 'Ads'],
    tags: ['copywriting', 'marketing', 'sales'],
  },
  {
    name: 'Notion AI',
    description: 'AI writing assistant integrated into Notion workspace',
    category: 'Productivity AI',
    website_url: 'https://notion.so',
    logo_url: 'https://logo.clearbit.com/notion.so',
    pricing_free: false,
    pricing_tier: 'paid',
    pricing_details: { monthly: '$10' },
    features: ['Writing assistance', 'Notion integration', 'Summarization', 'Translation'],
    use_cases: ['Note-taking', 'Documentation', 'Writing', 'Organization'],
    tags: ['notion', 'productivity', 'writing'],
  },
  {
    name: 'Grammarly',
    description: 'AI-powered writing assistant for grammar and style',
    category: 'Text AI',
    website_url: 'https://grammarly.com',
    logo_url: 'https://logo.clearbit.com/grammarly.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Basic' },
    features: ['Grammar check', 'Style suggestions', 'Tone detection', 'Plagiarism check'],
    use_cases: ['Writing', 'Editing', 'Professional communication'],
    tags: ['grammar', 'writing', 'editing'],
  },
  {
    name: 'Figma AI',
    description: 'AI features in Figma for design assistance',
    category: 'Productivity AI',
    website_url: 'https://figma.com',
    logo_url: 'https://logo.clearbit.com/figma.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Available' },
    features: ['Design generation', 'Auto-layout', 'Smart components', 'Design suggestions'],
    use_cases: ['UI design', 'Prototyping', 'Design automation'],
    tags: ['design', 'figma', 'ui'],
  },
  {
    name: 'Canva AI',
    description: 'AI-powered design tool with Magic Design features',
    category: 'Image AI',
    website_url: 'https://canva.com',
    logo_url: 'https://logo.clearbit.com/canva.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$13', free_tier: 'Limited' },
    features: ['Design generation', 'Text-to-image', 'Templates', 'Magic Eraser'],
    use_cases: ['Social media', 'Presentations', 'Marketing materials', 'Graphics'],
    tags: ['design', 'canva', 'graphics'],
  },
  {
    name: 'Adobe Firefly',
    description: 'Adobe\'s generative AI for images and text effects',
    category: 'Image AI',
    website_url: 'https://firefly.adobe.com',
    logo_url: 'https://logo.clearbit.com/adobe.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: 'Limited credits' },
    features: ['Text-to-image', 'Generative fill', 'Text effects', 'Commercial use'],
    use_cases: ['Image generation', 'Photo editing', 'Design', 'Marketing'],
    tags: ['adobe', 'generation', 'design'],
  },
  {
    name: 'ElevenLabs',
    description: 'AI voice generation and text-to-speech platform',
    category: 'Audio AI',
    website_url: 'https://elevenlabs.io',
    logo_url: 'https://logo.clearbit.com/elevenlabs.io',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: 'Limited' },
    features: ['Voice cloning', 'Text-to-speech', 'Voice library', 'Multi-language'],
    use_cases: ['Voiceovers', 'Audiobooks', 'Podcasts', 'Content creation'],
    tags: ['voice', 'audio', 'tts'],
  },
  {
    name: 'Murf',
    description: 'AI voice generator for professional voiceovers',
    category: 'Audio AI',
    website_url: 'https://murf.ai',
    logo_url: 'https://logo.clearbit.com/murf.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$19', free_tier: 'Limited' },
    features: ['Voice generation', 'Voice cloning', 'Voice changer', 'Studio quality'],
    use_cases: ['Voiceovers', 'Videos', 'Presentations', 'E-learning'],
    tags: ['voice', 'audio', 'professional'],
  },
  {
    name: 'Luma AI',
    description: 'AI-powered 3D capture and generation',
    category: 'Image AI',
    website_url: 'https://lumalabs.ai',
    logo_url: 'https://logo.clearbit.com/lumalabs.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['3D capture', '3D generation', 'Photorealistic', 'AR/VR support'],
    use_cases: ['3D modeling', 'E-commerce', 'AR/VR', 'Visualization'],
    tags: ['3d', 'capture', 'ar'],
  },
  {
    name: 'Remove.bg',
    description: 'AI background removal tool',
    category: 'Image AI',
    website_url: 'https://remove.bg',
    logo_url: 'https://logo.clearbit.com/remove.bg',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited' },
    features: ['Background removal', 'Batch processing', 'API access', 'High quality'],
    use_cases: ['Photo editing', 'E-commerce', 'Marketing', 'Design'],
    tags: ['background', 'editing', 'photo'],
  },
  {
    name: 'Upscale.media',
    description: 'AI image upscaling and enhancement',
    category: 'Image AI',
    website_url: 'https://upscale.media',
    logo_url: 'https://logo.clearbit.com/upscale.media',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited' },
    features: ['Image upscaling', 'Quality enhancement', 'Batch processing', 'API'],
    use_cases: ['Photo enhancement', 'Print quality', 'Restoration'],
    tags: ['upscale', 'enhancement', 'quality'],
  },
  {
    name: 'Descript',
    description: 'AI-powered video and audio editing platform',
    category: 'Video AI',
    website_url: 'https://descript.com',
    logo_url: 'https://logo.clearbit.com/descript.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$12', free_tier: 'Limited' },
    features: ['Text-based editing', 'Voice cloning', 'Overdub', 'Transcription'],
    use_cases: ['Video editing', 'Podcasts', 'Content creation', 'Transcription'],
    tags: ['video', 'editing', 'audio'],
  },
  {
    name: 'Luma Dream Machine',
    description: 'AI video generation from text prompts',
    category: 'Video AI',
    website_url: 'https://lumalabs.ai/dream-machine',
    logo_url: 'https://logo.clearbit.com/lumalabs.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Text-to-video', 'Fast generation', 'High quality', 'Custom styles'],
    use_cases: ['Video creation', 'Social media', 'Marketing', 'Content'],
    tags: ['video', 'generation', 'text-to-video'],
  },
  {
    name: 'HeyGen',
    description: 'AI video generation with avatars and voice cloning',
    category: 'Video AI',
    website_url: 'https://heygen.com',
    logo_url: 'https://logo.clearbit.com/heygen.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$24', free_tier: 'Limited' },
    features: ['AI avatars', 'Voice cloning', 'Multi-language', 'Templates'],
    use_cases: ['Training videos', 'Presentations', 'Marketing', 'E-learning'],
    tags: ['avatars', 'video', 'presentations'],
  },
  {
    name: 'Zapier',
    description: 'AI-powered workflow automation platform',
    category: 'Productivity AI',
    website_url: 'https://zapier.com',
    logo_url: 'https://logo.clearbit.com/zapier.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$20', free_tier: 'Limited tasks' },
    features: ['Workflow automation', 'AI actions', 'App integrations', 'No-code'],
    use_cases: ['Automation', 'Workflows', 'Integration', 'Productivity'],
    tags: ['automation', 'zapier', 'workflows'],
  },
  {
    name: 'Make (Integromat)',
    description: 'Visual platform for building AI-powered automations',
    category: 'Productivity AI',
    website_url: 'https://make.com',
    logo_url: 'https://logo.clearbit.com/make.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$9', free_tier: 'Limited' },
    features: ['Visual automation', 'AI modules', 'Complex workflows', 'API builder'],
    use_cases: ['Automation', 'Integration', 'Workflows', 'Business processes'],
    tags: ['automation', 'make', 'workflows'],
  },
  {
    name: 'ChatPDF',
    description: 'AI tool to chat with PDF documents',
    category: 'Productivity AI',
    website_url: 'https://chatpdf.com',
    logo_url: 'https://logo.clearbit.com/chatpdf.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$5', free_tier: 'Limited' },
    features: ['PDF chat', 'Document analysis', 'Summarization', 'Q&A'],
    use_cases: ['Document analysis', 'Research', 'Study', 'Information extraction'],
    tags: ['pdf', 'document', 'chat'],
  },
  {
    name: 'Otter.ai',
    description: 'AI meeting assistant with transcription and notes',
    category: 'Productivity AI',
    website_url: 'https://otter.ai',
    logo_url: 'https://logo.clearbit.com/otter.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited minutes' },
    features: ['Live transcription', 'Meeting notes', 'Action items', 'Integration'],
    use_cases: ['Meetings', 'Interviews', 'Lectures', 'Note-taking'],
    tags: ['transcription', 'meetings', 'notes'],
  },
  {
    name: 'Fireflies',
    description: 'AI meeting recorder and transcription tool',
    category: 'Productivity AI',
    website_url: 'https://fireflies.ai',
    logo_url: 'https://logo.clearbit.com/fireflies.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Limited' },
    features: ['Meeting recording', 'Transcription', 'AI summaries', 'Search'],
    use_cases: ['Meetings', 'Interviews', 'Documentation', 'Review'],
    tags: ['meetings', 'transcription', 'recording'],
  },
  {
    name: 'Character.ai',
    description: 'AI chatbot platform with customizable characters',
    category: 'Text AI',
    website_url: 'https://character.ai',
    logo_url: 'https://logo.clearbit.com/character.ai',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$10', free_tier: 'Available' },
    features: ['Character creation', 'Conversations', 'Roleplay', 'Custom personalities'],
    use_cases: ['Entertainment', 'Roleplay', 'Creative writing', 'Chat'],
    tags: ['chatbot', 'characters', 'entertainment'],
  },
  {
    name: 'Pi by Inflection',
    description: 'Personal AI assistant focused on helpful conversations',
    category: 'Text AI',
    website_url: 'https://inflection.ai/pi',
    logo_url: 'https://logo.clearbit.com/inflection.ai',
    pricing_free: true,
    pricing_tier: 'free',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Conversational AI', 'Personal assistant', 'Empathetic', 'Mobile app'],
    use_cases: ['Personal assistant', 'Conversations', 'Support', 'Companionship'],
    tags: ['assistant', 'personal', 'chat'],
  },
  {
    name: 'Hugging Face',
    description: 'Platform for AI models, datasets, and spaces',
    category: 'Code AI',
    website_url: 'https://huggingface.co',
    logo_url: 'https://logo.clearbit.com/huggingface.co',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: '$0', free_tier: 'Available' },
    features: ['Model hosting', 'Datasets', 'Spaces', 'Inference API'],
    use_cases: ['Model development', 'Research', 'Deployment', 'Experimentation'],
    tags: ['models', 'ml', 'open-source'],
  },
  {
    name: 'Replicate',
    description: 'Platform to run AI models with API',
    category: 'Code AI',
    website_url: 'https://replicate.com',
    logo_url: 'https://logo.clearbit.com/replicate.com',
    pricing_free: true,
    pricing_tier: 'freemium',
    pricing_details: { monthly: 'Pay per use', free_tier: 'Limited' },
    features: ['Model API', 'Fast inference', 'Auto-scaling', 'Many models'],
    use_cases: ['API integration', 'Model deployment', 'Experimentation'],
    tags: ['api', 'models', 'deployment'],
  },
];

async function seedTools() {
  console.log('Starting to seed tools...');
  
  for (const tool of initialTools) {
    try {
      const { data, error } = await supabase
        .from('tools')
        .upsert({
          name: tool.name,
          slug: slugify(tool.name),
          description: tool.description,
          category: tool.category,
          website_url: tool.website_url,
          logo_url: tool.logo_url,
          pricing_free: tool.pricing_free,
          pricing_tier: tool.pricing_tier,
          pricing_details: tool.pricing_details,
          features: tool.features,
          use_cases: tool.use_cases,
          tags: tool.tags,
        }, {
          onConflict: 'slug',
        });

      if (error) {
        console.error(`Error seeding ${tool.name}:`, error);
      } else {
        console.log(`✓ Seeded ${tool.name}`);
      }
    } catch (error) {
      console.error(`Error seeding ${tool.name}:`, error);
    }
  }
  
  console.log('Seeding complete!');
}

// Run if called directly
seedTools().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});

export { seedTools };
